pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.utils
import qs.theme
import qs.config

Singleton {
	function dummyInit() {}

	FileView {
		id: file

		readonly property string targetContents:
`// File automatically generated by ${Utils.shellName}.
// All changes made to this file will be discarded.
//
// For permanent changes to the Niri behavior, edit ~/.config/niri/config.kdl
// instead.

layout {
	gaps ${Config.wm.windowGaps}

	border {
		active-color "${Theme.palette.primary_fixed}"
		inactive-color "${Theme.palette.surface}"
		urgent-color "${Theme.palette.surface}"
	}
}

overview {
	backdrop-color "${Utils.blendColor(Theme.palette.background, Qt.rgba(0, 0, 0, 1), 0.3)}"
}

window-rule {
	geometry-corner-radius ${Config.rounding.window}
}

animations {
	workspace-switch {
		duration-ms ${Anims.workspaceSwitchDur}
		curve "ease-out-expo"
	}
}

output "*" {
	background-color "${Theme.palette.background}"
}`
		property bool ignoreThisChange: true
		onTargetContentsChanged: {
			if (ignoreThisChange == true) {
				ignoreThisChange = false
				return
			} else {
				file.tryWriteContents()
			}
		}

		path: Quickshell.env("HOME") + "/.config/niri/autogen.kdl"

		function tryWriteContents() {
			if (text() !== targetContents) {
				setText(targetContents)
			}
		}

		watchChanges: true
		Component.onCompleted: tryWriteContents()
		onFileChanged: tryWriteContents()
		onLoadFailed: (err) => {
			if (err === FileViewError.FileNotFound) tryWriteContents()
		}
	}
}
