pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.enums
import qs.theme
import qs.config
import qs.utils

Singleton {
	id: root

	function dummyInit() {}

	readonly property int workspaceSwitchDuration: Config.wm.workspaceSwitchDuration * Config.animations.speedMultiplier
	readonly property int workspaceSwitchEasing: Config.wm.workspaceSwitchEasing
	readonly property int horizontalViewMovementDuration: Config.wm.horizontalViewMovementDuration * Config.animations.speedMultiplier
	readonly property int horizontalViewMovementEasing: Config.wm.horizontalViewMovementEasing
	readonly property int overviewOpenCloseDuration: Config.wm.overviewOpenCloseDuration * Config.animations.speedMultiplier
	readonly property int overviewOpenCloseEasing: Config.wm.overviewOpenCloseEasing

	FileView {
		readonly property string targetContents:
`// File automatically generated by ${Utils.shellName}.
// All changes made to this file will be discarded.
//
// For permanent changes edit \`~/.config/niri/overrides.kdl\`

input {
	touchpad {
		tap
		natural-scroll
	}

	trackpoint {
		accel-speed 0.08
	}

	focus-follows-mouse
}

gestures {
	hot-corners {
		${Config.wm.useHotCorners ? "// off" : "off"}
	}
}

debug {
    honor-xdg-activation-with-invalid-serial
}

prefer-no-csd

layout {
	gaps ${Config.wm.windowGaps}
    center-focused-column "never"

    default-column-width { proportion 0.5; }

    focus-ring {
        off
    }

	border {
		width 4
		active-color "${Theme.palette.primary_fixed}"
		inactive-color "${Theme.palette.surface}"
		urgent-color "${Theme.palette.error}"
	}

    shadow {
        on
        softness 5
        spread 1
        offset x=2 y=2
        color "${Theme.palette.shadow}"
    }
}

spawn-sh-at-startup "${Quickshell.shellDir}/scripts/qs-safe-wrapper.sh"
spawn-sh-at-startup "${Quickshell.shellDir}/scripts/swayidle.sh"

hotkey-overlay {
    skip-at-startup
}

animations {
	workspace-switch {
		duration-ms ${root.workspaceSwitchDuration}
		curve "${NiriEasing.toNiriName(root.workspaceSwitchEasing)}"
	}
	horizontal-view-movement {
		duration-ms ${root.horizontalViewMovementDuration}
		curve "${NiriEasing.toNiriName(root.horizontalViewMovementEasing)}"
	}
	overview-open-close {
		duration-ms ${root.overviewOpenCloseDuration}
		curve "${NiriEasing.toNiriName(root.overviewOpenCloseEasing)}"
	}
}

output "*" {
	background-color "${Theme.palette.background}"
}

overview {
	backdrop-color "${Utils.blendColor(Theme.palette.background, Qt.rgba(0, 0, 0, 1), 0.3)}"
}

cursor {
	xcursor-theme "Bibata-Modern-Classic"
    hide-when-typing
}

window-rule {
	geometry-corner-radius ${Config.rounding.window}
	clip-to-geometry true
	open-maximized true
}

window-rule {
	match app-id="kitty"
	open-maximized false
}

window-rule {
    match app-id=r#"^org\.keepassxc\.KeePassXC$"#
    block-out-from "screencast"
}

screenshot-path "~/Pictures/Screenshots/Screenshot_%Y-%m-%d-%H%M%S.png"

binds {
    Mod+Shift+Slash { show-hotkey-overlay; }

    Mod+Q hotkey-overlay-title="Open a Terminal: kitty" repeat=false {
		spawn "kitty";
	}
    Mod+Space hotkey-overlay-title="Open the launcher" repeat=false {
		spawn-sh "qs ipc call floatingContent toggleLauncher";
	}
    Mod+Alt+L hotkey-overlay-title="Lock the Screen" repeat=false {
		spawn "${Paths.scriptsDir}/lock-screen.sh";
	}
    Mod+M hotkey-overlay-title="Open session management" repeat=false {
		spawn-sh "qs ipc call sessionManagement toggleOpen";
	}
	Print hotkey-overlay-title="Pick a region to screenshot" repeat=false {
		screenshot;
	}
	Shift+Print hotkey-overlay-title="Take a screenshot of the whole screen" repeat=false {
		screenshot-screen;
	}

	Alt+Right allow-when-locked=true repeat=false {
		spawn-sh "qs ipc call mediaControl next";
	}
	Alt+Left allow-when-locked=true repeat=false {
		spawn-sh "qs ipc call mediaControl previous";
	}
	Alt+Space allow-when-locked=true repeat=false {
		spawn-sh "qs ipc call mediaControl togglePlaying";
	}

    XF86AudioRaiseVolume allow-when-locked=true {
		spawn-sh "wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 0.1+";
	}
    XF86AudioLowerVolume allow-when-locked=true {
		spawn-sh "wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 0.1-";
	}
    XF86AudioMute allow-when-locked=true {
		spawn-sh "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
	}
    XF86AudioMicMute allow-when-locked=true {
		spawn-sh "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle";
	}

    XF86MonBrightnessUp allow-when-locked=true {
		spawn-sh "qs ipc call brightness increase"
	}
    XF86MonBrightnessDown allow-when-locked=true {
		spawn-sh "qs ipc call brightness decrease"
	}

    Mod+O repeat=false { toggle-overview; }
    Mod+X repeat=false { close-window; }

    Mod+Left  { focus-column-left; }
    Mod+Down  { focus-window-or-workspace-down; }
    Mod+Up    { focus-window-or-workspace-up; }
    Mod+Right { focus-column-right; }
    Mod+H     { focus-column-left; }
    Mod+J     { focus-window-or-workspace-down; }
    Mod+K     { focus-window-or-workspace-up; }
    Mod+L     { focus-column-right; }

    Mod+Shift+Left  { move-column-left; }
    Mod+Shift+Down  { move-window-down; }
    Mod+Shift+Up    { move-window-up; }
    Mod+Shift+Right { move-column-right; }
    Mod+Shift+H     { move-column-left; }
    Mod+Shift+J     { move-window-down; }
    Mod+Shift+K     { move-window-up; }
    Mod+Shift+L     { move-column-right; }

    Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
    Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
    Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
    Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

    Mod+WheelScrollRight      { focus-column-right; }
    Mod+WheelScrollLeft       { focus-column-left; }
    Mod+Ctrl+WheelScrollRight { move-column-right; }
    Mod+Ctrl+WheelScrollLeft  { move-column-left; }

    Mod+1 { focus-workspace 1; }
    Mod+2 { focus-workspace 2; }
    Mod+3 { focus-workspace 3; }
    Mod+4 { focus-workspace 4; }
    Mod+5 { focus-workspace 5; }
    Mod+6 { focus-workspace 6; }
    Mod+7 { focus-workspace 7; }
    Mod+8 { focus-workspace 8; }
    Mod+9 { focus-workspace 9; }
    Mod+Shift+1 { move-column-to-workspace 1; }
    Mod+Shift+2 { move-column-to-workspace 2; }
    Mod+Shift+3 { move-column-to-workspace 3; }
    Mod+Shift+4 { move-column-to-workspace 4; }
    Mod+Shift+5 { move-column-to-workspace 5; }
    Mod+Shift+6 { move-column-to-workspace 6; }
    Mod+Shift+7 { move-column-to-workspace 7; }
    Mod+Shift+8 { move-column-to-workspace 8; }
    Mod+Shift+9 { move-column-to-workspace 9; }

    Mod+F { maximize-column; }
    Mod+Shift+F repeat=false { fullscreen-window; }

    Mod+Minus { set-column-width "-10%"; }
    Mod+Equal { set-column-width "+10%"; }

    Mod+Shift+Minus { set-window-height "-10%"; }
    Mod+Shift+Equal { set-window-height "+10%"; }

    Mod+V       { toggle-window-floating; }
    Mod+Shift+V { switch-focus-between-floating-and-tiling; }

    // Applications such as remote-desktop clients and software KVM switches may
    // request that niri stops processing the keyboard shortcuts defined here
    // so they may, for example, forward the key presses as-is to a remote machine.
    // It's a good idea to bind an escape hatch to toggle the inhibitor,
    // so a buggy application can't hold your session hostage.
    //
    // The allow-inhibiting=false property can be applied to other binds as well,
    // which ensures niri always processes them, even when an inhibitor is active.
    Mod+Escape allow-inhibiting=false { toggle-keyboard-shortcuts-inhibit; }
}

// Put your overrides in this file instead
include "overrides.kdl"
`

		property bool ignoreThisChange: true
		onTargetContentsChanged: {
			if (ignoreThisChange == true) {
				ignoreThisChange = false
				return
			} else {
				tryWriteContents()
			}
		}

		path: Quickshell.env("HOME") + "/.config/niri/config.kdl"

		function tryWriteContents() {
			if (text() !== targetContents) {
				setText(targetContents)
			}
		}

		watchChanges: true
		Component.onCompleted: tryWriteContents()
		onFileChanged: tryWriteContents()
		onLoadFailed: (err) => {
			if (err === FileViewError.FileNotFound) tryWriteContents()
		}
	}

	FileView {
		id: overridesFile

		path: `${Quickshell.env("HOME")}/.config/niri/overrides.kdl`
		readonly property string defaultContents:
`// Here you can put all your overrides for the Niri config files generated by
// ${Utils.shellName}.

input {
    keyboard {
        xkb {
            layout "us"
        }
    }
}
`
		onLoadFailed: (err) => {
			if (err === FileViewError.FileNotFound) overridesFile.setText(overridesFile.defaultContents)
		}
	}
}
