pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.config
import qs.utils

Singleton {
	// Only writes the config when requested
	function write() {
		file.tryWriteContents()
	}

	FileView {
		id: file

		readonly property string targetContents: `// File automatically generated by ${Utils.shellName}.
// All changes made to this file will be discarded the next time you edit the
// shell's config.
//
// For permanent changes to the Niri behavior, edit ~/.config/niri/config.kdl
// instead.

layout {
	gaps ${Config.wm.windowGaps}

	border {
		active-color "${Theme.palette.accentBrighter}"
		inactive-color "${Theme.palette.background}"
		urgent-color "${Theme.palette.accent}"
	}
}

window-rule {
	geometry-corner-radius ${Config.rounding.window}
}

animations {
	workspace-switch {
		duration-ms ${Anims.workspaceSwitchDur}
		curve "ease-out-expo"
	}
}

output "*" {
	background-color "${Theme.palette.background}"
}`

		path: Quickshell.env("HOME") + "/.config/niri/autogen.kdl"

		function tryWriteContents() {
			if (text() !== targetContents) {
				setText(targetContents)
			}
		}

		watchChanges: true
		Component.onCompleted: tryWriteContents()
		onFileChanged: tryWriteContents()
		onLoadFailed: err => {
			if (err === FileViewError.FileNotFound)
			tryWriteContents()
		}
	}
}
