build-shaders:
	scripts/devtools/build-shaders.sh

clean-shaders:
	rm shaders/qsb/*

rebuild-shaders: clean-shaders && build-shaders

check-format:
	~/.local/share/chezmoi/scripts/fmt.sh --check

fmt:
	~/.local/share/chezmoi/scripts/fmt.sh
