build-shaders:
	scripts/build-shaders.sh

clean-shaders:
	rm ~/.cache/tpaau-shell/shaders-qsb/*

rebuild-shaders: 
	scripts/build-shaders.sh rebuild

check-format:
	~/.local/share/chezmoi/scripts/fmt.sh --check

fmt:
	~/.local/share/chezmoi/scripts/fmt.sh
