name: Checks

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check lock security
      run: ./scripts/checks/check-lock.sh
